### ISSUE TITLE
BleakError

### ISSUE THREAD

**Issue by reflektoin** [kbre93/every-breath-you-take#13]
Thanks for developing this, looks interesting!

I'm running on Linux Mint 21:
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
```

I got the following error:
```
Traceback (most recent call last):
  File "/home/vipera/gitrepot/every-breath-you-take/EBYT.py", line 23, in <module>
    loop.run_until_complete(plot.main())
  File "/home/vipera/gitrepot/every-breath-you-take/venv/lib/python3.10/site-packages/qasync/__init__.py", line 412, in run_until_complete
    return future.result()
  File "/home/vipera/gitrepot/every-breath-you-take/View.py", line 485, in main
    await asyncio.gather(self.model.update_ibi(), self.model.update_acc())
  File "/home/vipera/gitrepot/every-breath-you-take/Model.py", line 332, in update_acc
    await self.polar_sensor.start_acc_stream()
  File "/home/vipera/gitrepot/every-breath-you-take/PolarH10.py", line 277, in start_acc_stream
    await self.bleak_client.write_gatt_char(PolarH10.PMD_CHAR1_UUID, PolarH10.ACC_WRITE, response=True)
  File "/home/vipera/gitrepot/every-breath-you-take/venv/lib/python3.10/site-packages/bleak/__init__.py", line 769, in write_gatt_char
    raise BleakError("Characteristic {char_specifier} was not found!")
bleak.exc.BleakError: Characteristic {char_specifier} was not found!

```

So could be related to this package https://github.com/hbldh/bleak/ but I haven't yet researched it further.

**Comment by ar-jan** [comment]
Oops, you'd just posted this while I was looking into the same thing. It's the firmware: #14.

**Comment by reflektoin** [comment]
@ar-jan Thanks! That fixed my issue.
