### ISSUE TITLE
`bleak.exc.BleakDeviceNotFoundError`

### ISSUE THREAD

**Issue by egeres** [kbre93/every-breath-you-take#4]
After running `EBYT.py` I got the following error:

```
μ python EBYT.py
Looking for Polar device...
Found 15 BLE devices
Found Polar device
Traceback (most recent call last):
  File "C:\Github\every-breath-you-take\EBYT.py", line 23, in <module>
    loop.run_until_complete(plot.main())
  File "C:\Github\every-breath-you-take\venv\lib\site-packages\asyncqt\__init__.py", line 309, in run_until_complete
    return future.result()
  File "C:\Github\every-breath-you-take\View.py", line 484, in main
    await self.connect_polar()
  File "C:\Github\every-breath-you-take\View.py", line 412, in connect_polar
    await self.model.connect_sensor()
  File "C:\Github\every-breath-you-take\Model.py", line 92, in connect_sensor
    await self.polar_sensor.connect()
  File "C:\Github\every-breath-you-take\PolarH10.py", line 250, in connect
    await self.bleak_client.connect()
  File "C:\Github\every-breath-you-take\venv\lib\site-packages\bleak\__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
  File "C:\Github\every-breath-you-take\venv\lib\site-packages\bleak\backends\winrt\client.py", line 297, in connect
    self._requester = await self._create_requester(self._device_info)
  File "C:\Github\every-breath-you-take\venv\lib\site-packages\bleak\backends\winrt\client.py", line 264, in _create_requester
    raise BleakDeviceNotFoundError(
bleak.exc.BleakDeviceNotFoundError: Device with address C6:9F:5E:3C:08:ED was not found.
```

I'm not sure if I should first connect my polar device to my windows machine via bluetooth. I have tried physically plugging and unplugging the sensor from the strap, but this doesn't seem to work. Is it possible the problem has to do with a mismatch with the bluetooth ID of my device and what the script is looking for?

**Comment by egeres** [comment]
Okay, it seems my polar was connected with an app called [polar sensor logger](https://play.google.com/store/apps/details?id=com.j_ware.polarsensorlogger&hl=en_US) which was gathering data at the time. I don't know how the ANT+ protocol works, but is it possible to check if a device has been found but it's being used by a different system?

**Comment by kbre93** [comment]
@egeres is it working for you if you disconnect it from the Polar Sensor Logger?

**Comment by egeres** [comment]
Oops, I didn't clarify that! **yes**, it works if I disconnect the polar sensor logger!! Should this issue be closed, or is the detection of the device being used something that belongs here?
